---
- name: Symlink .zshrc
  file:
    src: "{{ repo_root }}/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: true

- name: Get zsh path
  command: which zsh
  register: zsh_path
  changed_when: false

- name: Ensure zsh is in /etc/shells
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
    state: present
  become: true

- name: Change default shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_path.stdout }}"
  when: ansible_env.SHELL != zsh_path.stdout
  become: true
