---
- name: Include directory creation tasks
  include_tasks: directories.yml

- name: Include Debian package tasks
  include_tasks: packages-debian.yml
  when: ansible_os_family == "Debian"

- name: Include macOS package tasks
  include_tasks: packages-darwin.yml
  when: is_macos | default(false)

- name: Configure WSL environment
  include_tasks: wsl-config.yml
  when: is_wsl | default(false)

- name: Display environment info
  debug:
    msg:
      - "Home: {{ ansible_env.HOME }}"
      - "User: {{ ansible_env.USER }}"
      - "OS Family: {{ ansible_os_family }}"
      - "Is WSL: {{ is_wsl | default(false) }}"
      - "Is macOS: {{ is_macos | default(false) }}"
