---
- name: Detect system Python interpreter with apt support
  raw: |
    for python in /usr/bin/python3 /usr/bin/python3.* /bin/python3; do
      if [ -x "$python" ] && $python -c "import apt" 2>/dev/null; then
        echo "$python"
        exit 0
      fi
    done
    # If no Python with apt found, return system python3
    echo "/usr/bin/python3"
  args:
    executable: /bin/bash
  register: detected_python
  changed_when: false

- name: Set ansible_python_interpreter to detected Python
  set_fact:
    ansible_python_interpreter: "{{ detected_python.stdout | trim }}"

- name: Bootstrap python3-apt for system Python (if needed)
  raw: |
    if ! dpkg -l python3-apt 2>/dev/null | grep -q '^ii'; then
      apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get install -y python3-apt
    fi
  args:
    executable: /bin/bash
  become: true
  changed_when: false

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: install_packages | bool

- name: Install core packages (Debian/Ubuntu)
  apt:
    name:
      - git
      - curl
      - wget
      - tree
      - build-essential
      - gpg
      - ffmpeg
      - subversion
    state: present
  become: true
  when: install_packages | bool

- name: Install libgd-dev (Debian/Ubuntu)
  apt:
    name: libgd-dev
    state: present
  become: true
  when: install_packages | bool
  ignore_errors: true
  register: libgd_result

- name: Install libgdbm-dev (Debian/Ubuntu)
  apt:
    name: libgdbm-dev
    state: present
  become: true
  when: install_packages | bool
  ignore_errors: true
  register: libgdbm_result

- name: Display development libraries installation status
  debug:
    msg:
      - "libgd-dev: {{ 'installed' if libgd_result is succeeded else 'skipped (version conflict with sury.org repository)' }}"
      - "libgdbm-dev: {{ 'installed' if libgdbm_result is succeeded else 'skipped' }}"
  when: install_packages | bool

- name: Install Node.js packages (Debian/Ubuntu)
  apt:
    name:
      - nodejs
      - npm
    state: present
  become: true
  when: install_packages | bool
  ignore_errors: true
  register: nodejs_result

- name: Display Node.js installation status
  debug:
    msg: "Node.js installation {{ 'succeeded' if nodejs_result is succeeded else 'failed - may already be installed from NodeSource' }}"
  when: install_packages | bool

- name: Install hub (Debian/Ubuntu)
  apt:
    name: hub
    state: present
  become: true
  when: install_packages | bool
  ignore_errors: true
  register: hub_result

- name: Display hub installation status
  debug:
    msg: "Hub installation {{ 'succeeded' if hub_result is succeeded else 'failed - skipping' }}"
  when: install_packages | bool

- name: Install bun (Debian/Ubuntu)
  shell: curl -fsSL https://bun.sh/install | bash
  args:
    creates: "{{ ansible_env.HOME }}/.bun/bin/bun"
  when:
    - install_packages | bool
    - ansible_os_family == "Debian"
