---
package_manager: homebrew

homebrew_packages:
  - tmux
  - zsh
  - eza
  - bat
  - the_silver_searcher
  - fzf
  - hub
  - node
  - bun
  - curl
  - wget
  - ffmpeg
  - gd
  - gdbm
  - subversion
  - 1password-cli

homebrew_taps:
  - homebrew/cask-fonts

homebrew_cask_packages:
  - font-meslo-lg-nerd-font
  - postman
  - spotify
  - docker
  - iterm2
  - google-chrome
  - firefox
  - tableplus
  - cursor
  - wordpress-studio
