---
- name: Install neovim packages (Debian/Ubuntu)
  apt:
    name: "{{ debian_packages }}"
    state: present
  become: true
  when:
    - install_packages | bool
    - ansible_os_family == "Debian"

- name: Install neovim packages (macOS)
  homebrew:
    name: "{{ darwin_packages }}"
    state: present
  when:
    - install_packages | bool
    - is_macos | default(false)

- name: Install Python packages for neovim
  pip:
    name: "{{ python_packages }}"
    state: present
    extra_args: --user
  when: install_packages | bool
